### ISSUE TITLE
this only works on windows? 

### ISSUE THREAD

**Issue by TheBigBear** [MSEndpointMgr/EDGEProfiles#2]
Hi @mardahl 
Thanks for doing this. do you have any idea what it would take to make this work on Mac ( and linux ) too? 
I see some of the data lives in the windows 'registry', the coolest solution would be if one could backup and restore these profiles across OS boundaries ... eventually ...

**Comment by mardahl** [comment]
Thanks TheBigBear.
Unfortunately, I am without a MacOS device to test/develop on. 
But yeah, a conversion would be nice, so some sort of roaming could take place - albeit it might take some time.
